repos:

  # Official Ruff pre-commit hook
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version
  rev: v0.6.9
  hooks:
    # Linting
    - id: ruff
      args: [--config=ruff.toml, --fix]
    # Formatting
    - id: ruff-format