llm: 
    "api": "sambastudio"
    "do_sample": False
    "temperature": 0.01
    "streaming": False
    "max_tokens_to_generate": 1200
    "coe": True 
    "select_expert": "Meta-Llama-3-70B-Instruct-8192"
    "process_prompt": False
