api: "sncloud" #  set either sambastudio or sncloud

llm: 
    "do_sample": False
    "temperature": 0.7
    "streaming": True
    "max_tokens_to_generate": 1200
    "coe": False 
    "select_expert": "Meta-Llama-3.1-8B-Instruct"
    "process_prompt": False
